### PR TITLE
Added a time travel box and a level for it. 

### PR DESCRIPTION
**Pull request by Norbert515**
The time travel box teleports the entity back on collision after x amounts of seconds

### CODE REVIEW

**Comment by fuchss-dominik** [comment]
Nice block. Would you like to create this block and level as a mod for rekit (see https://github.com/fuchss-dominik/rekit-sample-mod) ?

**Comment by matzebond** [comment]
Less work for us + our first user contributed mod :-)
Is it possible to build a level with a block added by a mod?

**Comment by fuchss-dominik** [comment]
Sure. See sample mod.

**Comment by fuchss-dominik** [comment]
Shall be added to this project as mod (if possible).

**Pull request closed without merging**
